# Generated by Django 4.2.13 on 2024-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_co_subm_day',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_co_subm_day',
            field=models.TextField(null=True),
        ),
    ]
