# Generated by Django 4.2.13 on 2024-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_depositoption_intr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
