# Generated by Django 4.2.13 on 2024-05-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_depositoption_intr_rate2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
