# Generated by Django 4.2.13 on 2024-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUR_UNIT', models.CharField(blank=True, max_length=3, null=True)),
                ('CUR_NM', models.CharField(blank=True, max_length=100, null=True)),
                ('TTB', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TTS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DEAL_BAS_R', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BKPR', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
