# Generated by Django 4.2.13 on 2024-05-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('cur_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('ttb', models.FloatField(blank=True, null=True)),
                ('tts', models.FloatField(blank=True, null=True)),
                ('deal_bas_r', models.FloatField(blank=True, null=True)),
                ('bkpr', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
