# Generated by Django 4.2.13 on 2024-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
