# Generated by Django 4.2.13 on 2024-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_bank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_savings',
            field=models.IntegerField(null=True),
        ),
    ]
