# Generated by Django 4.2.13 on 2024-05-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_depositproduct_fin_co_subm_day_and_more'),
        ('accounts', '0002_alter_user_annual_income_alter_user_primary_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('saving_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.savingoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('deposit_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.depositoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_deposits',
            field=models.ManyToManyField(through='accounts.SubscribedDeposit', to='products.depositoption'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_savings',
            field=models.ManyToManyField(through='accounts.SubscribedSaving', to='products.savingoption'),
        ),
    ]
