# Generated by Django 4.2.13 on 2024-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_depositproduct_fin_co_subm_day_and_more'),
        ('accounts', '0004_alter_user_subscribed_deposits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeddeposit',
            name='intr_rate',
        ),
        migrations.RemoveField(
            model_name='subscribeddeposit',
            name='intr_rate2',
        ),
        migrations.RemoveField(
            model_name='subscribedsaving',
            name='intr_rate',
        ),
        migrations.RemoveField(
            model_name='subscribedsaving',
            name='intr_rate2',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_deposits',
            field=models.ManyToManyField(through='accounts.SubscribedDeposit', to='products.depositoption'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_savings',
            field=models.ManyToManyField(through='accounts.SubscribedSaving', to='products.savingoption'),
        ),
    ]
