# Generated by Django 4.2.13 on 2024-05-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_depositproduct_fin_co_subm_day_and_more'),
        ('accounts', '0005_remove_subscribeddeposit_intr_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeddeposit',
            name='deposit_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_subscribed', to='products.depositoption'),
        ),
        migrations.AlterField(
            model_name='subscribedsaving',
            name='saving_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_subscribed', to='products.savingoption'),
        ),
    ]
